### ISSUE TITLE
DeprecationWarning: asyncio.get_event_loop()

### ISSUE THREAD

**Issue by wastu01** [Z1xus/self-reaction-bot#4]
The script runs successfully; however, it triggers a deprecation warning:

```
eprecationWarning: There is no current event loop
loop = asyncio.get_event_loop() # 獲取當前事件循環
```

Consider updating this part to use `asyncio.run()` for better compatibility with newer Python versions.

**Comment by wastu01** [comment]
btw I find two of emoji / letter website. 
if somebody need to copy and paste
[https://www.webfx.com/tools/emoji-cheat-sheet/](https://www.webfx.com/tools/emoji-cheat-sheet/)
[https://lingojam.com/RegionalIndicator](https://lingojam.com/RegionalIndicator)

**Comment by Z1xus** [comment]
fixed. thanks for reporting that, and for your support 👍
